// <auto-generated />
using System;
using Masterklub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masterklub.Infrastructure.Migrations
{
    [DbContext(typeof(MasterklubDbContext))]
    [Migration("20260917220205_DodajSeedPodatke")]
    partial class DodajSeedPodatke
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masterklub.Domain.Entities.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipKorisnika")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnici", (string)null);

                    b.HasDiscriminator<string>("TipKorisnika").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Nagrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojPoena")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Nivo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Nagrade", null, t =>
                        {
                            t.HasCheckConstraint("CK_Nagrada_BrojPoena", "[BrojPoena] >= 0");

                            t.HasCheckConstraint("CK_Nagrada_Nivo", "[Nivo] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojPoena = 10,
                            Naziv = "Poklon bon 2000 RSD",
                            Nivo = 1,
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 2,
                            BrojPoena = 20,
                            Naziv = "Bežične slušalice",
                            Nivo = 2,
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            BrojPoena = 35,
                            Naziv = "Pametni sat",
                            Nivo = 3,
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 4,
                            BrojPoena = 60,
                            Naziv = "Vikend paket za dvoje",
                            Nivo = 5,
                            Status = "Aktivan"
                        });
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.NarudzbinaNagrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojPoenaOduzetih")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNarudzbine")
                        .HasColumnType("datetime2");

                    b.Property<int>("NagradaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdavacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NagradaId");

                    b.HasIndex("ProdavacId");

                    b.ToTable("NarudzbineNagrada", null, t =>
                        {
                            t.HasCheckConstraint("CK_NarudzbinaNagrade_BrojPoenaOduzetih", "[BrojPoenaOduzetih] >= 0");
                        });
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Prodaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojBodovaOstvarenih")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumProdaje")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("ProdavacId")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdavacId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("Prodaje", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prodaja_BrojBodovaOstvarenih", "[BrojBodovaOstvarenih] >= 0");

                            t.HasCheckConstraint("CK_Prodaja_Kolicina", "[Kolicina] > 0");
                        });
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojBodova")
                        .HasColumnType("int");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Proizvodi", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proizvod_BrojBodova", "[BrojBodova] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojBodova = 30,
                            Kategorija = "TV",
                            Naziv = "Televizor Samsung 43\"",
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 2,
                            BrojBodova = 50,
                            Kategorija = "TV",
                            Naziv = "Televizor LG 55\"",
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            BrojBodova = 15,
                            Kategorija = "AparatiZaKucu",
                            Naziv = "Usisivač Bosch",
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 4,
                            BrojBodova = 40,
                            Kategorija = "AparatiZaKucu",
                            Naziv = "Veš mašina Gorenje",
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 5,
                            BrojBodova = 25,
                            Kategorija = "Klime",
                            Naziv = "Klima Midea 12000 BTU",
                            Status = "Aktivan"
                        },
                        new
                        {
                            Id = 6,
                            BrojBodova = 45,
                            Kategorija = "Klime",
                            Naziv = "Klima Daikin 18000 BTU",
                            Status = "Aktivan"
                        });
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Administrator", b =>
                {
                    b.HasBaseType("Masterklub.Domain.Entities.Korisnik");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@masterklub.rs",
                            Ime = "Petar",
                            LozinkaHash = "AQAAAAEAAYagAAAAEF8syByupmhPOCxWOv7k+9nuPtGqllrQoQQGazauFnAtVM5oknUXA8gaHgZR7tIK1Q==",
                            Prezime = "Petrović",
                            Status = "Aktivan"
                        });
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Prodavac", b =>
                {
                    b.HasBaseType("Masterklub.Domain.Entities.Korisnik");

                    b.Property<int>("BrojPoena")
                        .HasColumnType("int");

                    b.Property<int>("Nivo")
                        .HasColumnType("int");

                    b.Property<string>("TipProdavca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UkupnoOstvarenihBodova")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Prodavac_BrojPoena", "[BrojPoena] >= 0");

                            t.HasCheckConstraint("CK_Prodavac_Nivo", "[Nivo] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Prodavac_UkupnoOstvarenihBodova", "[UkupnoOstvarenihBodova] >= 0");
                        });

                    b.HasDiscriminator().HasValue("Prodavac");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "marko@masterklub.rs",
                            Ime = "Marko",
                            LozinkaHash = "AQAAAAEAAYagAAAAEGjTLdohWuB5XfYIxllgLOOj8hB1KUCE6JuKKbi5G3KlunRZs428WUUYiIiAeYawrA==",
                            Prezime = "Marković",
                            Status = "Aktivan",
                            BrojPoena = 0,
                            Nivo = 1,
                            TipProdavca = "Prodavac",
                            UkupnoOstvarenihBodova = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "ana@masterklub.rs",
                            Ime = "Ana",
                            LozinkaHash = "AQAAAAEAAYagAAAAEGjTLdohWuB5XfYIxllgLOOj8hB1KUCE6JuKKbi5G3KlunRZs428WUUYiIiAeYawrA==",
                            Prezime = "Anić",
                            Status = "Aktivan",
                            BrojPoena = 0,
                            Nivo = 1,
                            TipProdavca = "Prodavac",
                            UkupnoOstvarenihBodova = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "jovan@masterklub.rs",
                            Ime = "Jovan",
                            LozinkaHash = "AQAAAAEAAYagAAAAEGjTLdohWuB5XfYIxllgLOOj8hB1KUCE6JuKKbi5G3KlunRZs428WUUYiIiAeYawrA==",
                            Prezime = "Jovanović",
                            Status = "Aktivan",
                            BrojPoena = 0,
                            Nivo = 1,
                            TipProdavca = "Menadzer",
                            UkupnoOstvarenihBodova = 0
                        });
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.NarudzbinaNagrade", b =>
                {
                    b.HasOne("Masterklub.Domain.Entities.Nagrada", "Nagrada")
                        .WithMany("NarudzbineNagrada")
                        .HasForeignKey("NagradaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Masterklub.Domain.Entities.Prodavac", "Prodavac")
                        .WithMany("NarudzbineNagrada")
                        .HasForeignKey("ProdavacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nagrada");

                    b.Navigation("Prodavac");
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Prodaja", b =>
                {
                    b.HasOne("Masterklub.Domain.Entities.Prodavac", "Prodavac")
                        .WithMany("Prodaje")
                        .HasForeignKey("ProdavacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Masterklub.Domain.Entities.Proizvod", "Proizvod")
                        .WithMany("Prodaje")
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prodavac");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Nagrada", b =>
                {
                    b.Navigation("NarudzbineNagrada");
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Proizvod", b =>
                {
                    b.Navigation("Prodaje");
                });

            modelBuilder.Entity("Masterklub.Domain.Entities.Prodavac", b =>
                {
                    b.Navigation("NarudzbineNagrada");

                    b.Navigation("Prodaje");
                });
#pragma warning restore 612, 618
        }
    }
}
